# conda env for binder
name: sk-eval

channels:
  - conda-forge

dependencies:
  - python=3.10
  - lxml # for pandas.read_html, used in NotebookCollection
  - pip
  - scikit-learn>=1.2
  - matplotlib
  # for pandas.read_html (optional dependency for NotebookCollection)
  - lxml
  - pip:
    - .
    # NotebookCollection example needs jupytext
    # we pin these versions because it'll break
    # with most recent ones. I think it's due to
    # an incompatibility between jupytext
    # and jupyter-server
    - jupytext<1.15
    - jupyterlab<4
    - jupyter-server<2
    - ploomber-engine
    - seaborn
    - ipywidgets
    - jupysql
    
